name: Build and deploy ASP.Net Core app to Azure Web App - MyVote

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set environment to production
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "VITE_HTTPS=false" >> $GITHUB_ENV
          echo "ASPNETCORE_URLS=http://localhost:5000" >> $GITHUB_ENV
          echo "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" >> $GITHUB_ENV  # Prevents HTTPS issues

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Remove all HTTPS certificates (Final Fix)
        run: |
          dotnet dev-certs https --clean
          mkdir -p ~/.aspnet/https && chmod 777 ~/.aspnet/https
        continue-on-error: true  # Don't fail if no certs exist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps
        working-directory: myvote.client

      - name: Run frontend tests
        run: npm test
        working-directory: myvote.client
        env:
          VITE_HTTPS: false

      - name: Build frontend
        run: npm run build
        working-directory: myvote.client
        env:
          VITE_HTTPS: false

      - name: Restore backend dependencies
        run: dotnet restore
        working-directory: myvote.server

      - name: Run backend tests
        run: dotnet test --no-restore --verbosity normal
        working-directory: myvote.server
        env:
          ASPNETCORE_URLS: http://localhost:5000
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1  # Another HTTPS fix

      - name: Build backend
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish
        working-directory: myvote.server
        env:
          ASPNETCORE_URLS: http://localhost:5000
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

      - name: Verify published files
        run: dir ${{ github.workspace }}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/publish
          retention-days: 1

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ${{ github.workspace }}/dotnet-app

      - name: Verify downloaded files
        run: dir ${{ github.workspace }}/dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyVote'
          slot-name: 'Production'
          package: ${{ github.workspace }}/dotnet-app
